import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Mobile App Development in Ireland | iOS & Android | Square Root Solutions",
  description: "Mobile app development company in Dublin. Native and cross-platform iOS and Android apps connected to your back office, data and AI — built for performance and reliability.",
  alternates: { canonical: "/mobile-development" },
  openGraph: {
    title: "Mobile App Development in Ireland | iOS & Android | Square Root Solutions",
    description: "Mobile app development company in Dublin. Native and cross-platform iOS and Android apps connected to your back office, data and AI — built for performance and reliability.",
    url: "/mobile-development",
    type: 'website',
    siteName: 'Square Root Solutions',
    locale: 'en_IE',
  },
};

export default function MobileDevelopmentPage() {
  return (
    <>
<section className="page-hero"><div className="wrap"><div className="crumbs"><a href="/">Home</a><span className="sep">/</span><a href="/services">Services</a><span className="sep">/</span><span>Mobile Apps</span></div><div className="page-hero-grid"><div><span className="eyebrow"><span className="dot"></span> Mobile App Development · Dublin</span><h1>Mobile apps your customers <span className="accent-word">keep</span> on their home screen.</h1><p className="lede">Native and cross-platform iOS and Android apps, engineered to feel fast, work offline, and connect cleanly to the systems and data running your business.</p><div className="hero-actions"><a className="cta-btn primary" href="/contact">Book a discovery call <span className="arrow">→</span></a><a className="ghost-btn" href="#features">See capabilities</a></div></div><dl className="page-hero-meta"><dt>Platforms</dt><dd>iOS · Android · cross-platform</dd><dt>Stack</dt><dd>Swift · Kotlin · React Native · Flutter</dd><dt>Connected</dt><dd>APIs · push · offline sync · payments</dd><dt>Delivery</dt><dd>MVP in 8–14 weeks</dd></dl></div></div></section>
<section className="s soft"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">01</span> The problem</span><h2>Why so many apps quietly fail.</h2></div><p className="section-intro">Most app problems aren't about ideas — they're about performance, connection and the gap between launch and real use.</p></div><div className="q-grid"><div className="q-card"><div className="marker">1</div><h3>Slow, janky experience</h3><p>Laggy screens and clunky navigation that feel worse than the website, so users uninstall within a week.</p></div><div className="q-card"><div className="marker">2</div><h3>Disconnected from your systems</h3><p>An app that can't see your live inventory, orders or customer data because it was never properly integrated.</p></div><div className="q-card"><div className="marker">3</div><h3>Breaks offline</h3><p>Apps that fall apart the moment connectivity drops — useless for field, retail or travel use.</p></div><div className="q-card"><div className="marker">4</div><h3>Stalls after launch</h3><p>No analytics, no update path and no plan for the App Store review and release cycle.</p></div></div></div></section>
<section className="s" id="features"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">02</span> What we deliver</span><h2>From MVP to a polished, connected app.</h2></div><p className="section-intro">We take mobile products from concept to the stores — and keep them healthy afterwards.</p></div><div className="who-grid"><div className="who-card"><span className="label">Native</span><h3>Native iOS &amp; Android</h3><p>Platform-native apps where performance, hardware access or platform feel matter most.</p><ul><li>Swift / SwiftUI for iOS</li><li>Kotlin for Android</li><li>Deep platform integration</li></ul></div><div className="who-card"><span className="label">Cross-platform</span><h3>Cross-platform apps</h3><p>One codebase across iOS and Android when speed-to-market and budget are priorities.</p><ul><li>React Native &amp; Flutter</li><li>Shared business logic</li><li>Faster iteration</li></ul></div><div className="who-card"><span className="label">Connected</span><h3>Back-end &amp; integration</h3><p>The APIs, sync and infrastructure that make the app part of your wider system.</p><ul><li>API &amp; back-end build</li><li>Offline-first sync</li><li>Push, payments &amp; auth</li></ul></div></div></div></section>
<section className="s soft"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">03</span> Capabilities</span><h2>What makes an app worth keeping.</h2></div><p className="section-intro">The engineering details users never see but always feel.</p></div><div className="q-grid three"><div className="q-card"><div className="marker">⚡</div><h3>Native performance</h3><p>Smooth 60fps interfaces and fast startup, profiled and optimised on real devices.</p></div><div className="q-card"><div className="marker">⤓</div><h3>Offline-first</h3><p>Local storage and conflict-aware sync so the app keeps working without a connection.</p></div><div className="q-card"><div className="marker">🔔</div><h3>Push &amp; engagement</h3><p>Reliable push notifications and deep links that bring users back at the right moment.</p></div><div className="q-card"><div className="marker">§</div><h3>Secure by design</h3><p>Secure storage, biometric auth and GDPR-aligned data handling built in.</p></div><div className="q-card"><div className="marker">◷</div><h3>Analytics &amp; crash reporting</h3><p>Know how the app is used and catch issues before they spread, from day one.</p></div><div className="q-card"><div className="marker">↻</div><h3>CI/CD to the stores</h3><p>Automated builds and releases so updates ship quickly and predictably.</p></div></div></div></section>
<section className="s dark"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">04</span> How we deliver</span><h2>A delivery process built to reduce risk.</h2></div><p className="section-intro">Structured, sprint-based delivery with visibility at every stage — and your existing systems protected throughout.</p></div><div className="steps"><div className="step"><div className="step-num">1<small>Discovery</small></div><div><h3>Audit &amp; scope</h3><p>We map your goals, systems, data and constraints, then produce a written scope with timeline and fixed-price proposal before any build.</p></div></div><div className="step"><div className="step-num">2<small>Design</small></div><div><h3>Architecture</h3><p>A solution architecture mapped to your environment, with a phased delivery roadmap agreed up front.</p></div></div><div className="step"><div className="step-num">3<small>Build</small></div><div><h3>Sprint delivery</h3><p>Working software reviewed every two weeks. Continuous progress you can see and steer.</p></div></div><div className="step"><div className="step-num">4<small>Validate</small></div><div><h3>Testing &amp; UAT</h3><p>Functional, performance and security testing plus user acceptance in a production-mirroring sandbox.</p></div></div><div className="step"><div className="step-num">5<small>Launch</small></div><div><h3>Rollout &amp; support</h3><p>Phased go-live with monitoring from day one, training, documentation and ongoing optimisation.</p></div></div></div></div></section>
<section className="s"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">05</span> Tech stack</span><h2>The mobile toolkit we trust.</h2></div><p className="section-intro">Chosen per project based on performance needs, budget and your existing systems.</p></div><div className="tech-grid"><div className="tech-tile"><div className="glyph"></div><span>Swift<small>iOS native</small></span></div><div className="tech-tile"><div className="glyph">K</div><span>Kotlin<small>Android</small></span></div><div className="tech-tile"><div className="glyph">⚛</div><span>React Native<small>Cross-platform</small></span></div><div className="tech-tile"><div className="glyph">◆</div><span>Flutter<small>Cross-platform</small></span></div><div className="tech-tile"><div className="glyph">🔥</div><span>Firebase<small>Back-end</small></span></div><div className="tech-tile"><div className="glyph">◳</div><span>Azure<small>Cloud</small></span></div><div className="tech-tile"><div className="glyph">⊞</div><span>GraphQL<small>APIs</small></span></div><div className="tech-tile"><div className="glyph">🔔</div><span>FCM/APNs<small>Push</small></span></div><div className="tech-tile"><div className="glyph">💳</div><span>Stripe<small>Payments</small></span></div><div className="tech-tile"><div className="glyph">↻</div><span>Fastlane<small>Releases</small></span></div></div></div></section>
<section className="s soft"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">06</span> Use cases</span><h2>Apps we're asked to build.</h2></div><p className="section-intro">Common mobile products across our clients.</p></div><div className="q-grid"><div className="q-card"><div className="marker">🛍</div><h3>Commerce &amp; loyalty</h3><p>Shopping, ordering and loyalty apps connected to live catalogue, payments and CRM.</p></div><div className="q-card"><div className="marker">🧰</div><h3>Field &amp; ops apps</h3><p>Offline-capable tools for field teams — inspections, jobs, deliveries and data capture.</p></div><div className="q-card"><div className="marker">◧</div><h3>Customer companions</h3><p>Apps that extend a SaaS or service into customers' pockets with real-time data.</p></div><div className="q-card"><div className="marker">❤</div><h3>Health &amp; wellness</h3><p>Tracking and engagement apps with secure data handling and integrations.</p></div></div></div></section>
<section className="s"><div className="wrap"><div className="section-head"><div><span className="section-tag"><span className="num">07</span> Why Square Root</span><h2>Why teams choose us for this work.</h2></div><p className="section-intro">Engineering depth, API-first thinking and GDPR-aligned delivery — focused on systems that last.</p></div><div className="why-grid"><div className="why-row"><div className="ic">⚡</div><p><b>Performance obsessives.</b> We profile on real devices and treat smoothness as a requirement, not a nice-to-have.</p></div><div className="why-row"><div className="ic">⇄</div><p><b>Properly connected.</b> We build the back-end and integrations too, so the app is part of your system — not an island.</p></div><div className="why-row"><div className="ic">↻</div><p><b>Beyond launch.</b> Store submissions, analytics, updates and iteration are part of how we work, not an afterthought.</p></div><div className="why-row"><div className="ic">◇</div><p><b>Right tool per project.</b> Native or cross-platform — we recommend based on your needs, not our preferences.</p></div></div></div></section>
<section className="s soft"><div className="wrap narrow"><div className="section-head" style={{ gridTemplateColumns: "1fr" }}><div><span className="section-tag"><span className="num">08</span> FAQ</span><h2>Frequently asked questions.</h2></div></div><div className="faq"><details className="faq-item"><summary>Native or cross-platform — which should we choose?</summary><div className="answer"><p>It depends on your priorities. Cross-platform (React Native or Flutter) is faster and cheaper for most business apps. Native makes sense when you need maximum performance, heavy hardware use or platform-specific polish. We advise based on your case during discovery.</p></div></details><details className="faq-item"><summary>How much does a mobile app cost?</summary><div className="answer"><p>Most apps range from €25,000 for a focused MVP to €90,000+ for a full product with custom back-end. A discovery workshop produces a fixed-price proposal before development.</p></div></details><details className="faq-item"><summary>How long until launch?</summary><div className="answer"><p>A well-scoped MVP typically reaches the stores in 8–14 weeks. Larger products with complex back-ends take longer; we deliver in sprints so you see progress throughout.</p></div></details><details className="faq-item"><summary>Do you handle App Store and Play Store submission?</summary><div className="answer"><p>Yes — we manage the full submission and review process, set up automated release pipelines, and can maintain your store presence after launch.</p></div></details><details className="faq-item"><summary>Can the app work with our existing systems?</summary><div className="answer"><p>Yes. We build the APIs and integrations to connect your app to your CRM, inventory, payments and data, so it reflects live business information.</p></div></details></div></div></section>
<section className="s"><div className="wrap"><div className="ready-cta"><div><h3>Have a mobile product in mind?</h3><p>Tell us what it needs to do and who it's for. We'll propose the right platform, scope and timeline.</p></div><a className="cta-btn" href="/contact">Book a discovery call <span className="arrow">→</span></a></div></div></section>
    </>
  );
}
